baseURL = "https://www.podletter.club/"
languageCode = "zh-CN"
title = "PodLetter 播客简报导航"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
[params]
  author = "FinnYan"
  description = "播客简报导航"
